### ISSUE TITLE
cursor image pixelated  on chrome (mac) 

### ISSUE THREAD

**Issue by tiagogon** [tholman/intense-images#41]
the cursor gets pixelated on Chrome 46.0.2490.80 (Mac): http://oi68.tinypic.com/egvkoz.jpg

on safari looks great!

**Comment by slcr** [comment]
+1

**Comment by tholman** [comment]
Oh gross! Strange... Definitely going to fix!

**Comment by tholman** [comment]
Right! Got to the bottom of this (thankfully!)

This bug was accidentally introduced into chrome v46 -- A fix has been accepted for v47, so we'll be all good after that! Here's the bug, if anyone wants to star, or follow.

https://code.google.com/p/chromium/issues/detail?id=543310&q=label%3Acr-internals&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

Chrome definitely isn't what it used to be... but oh well, I feel comfortable closing this (there isn't really much I can do anyway).

**Comment by tiagogon** [comment]
with the the beta version 47.0.2526.58 beta (64-bit), the issue is fixed. ;)
